---
- name: Rekick and wait for nodes to become available
  delegate_to: localhost
  rekick:
    host_ip: "{{ ansible_ssh_host }}"
    host_name: "{{ inventory_hostname }}"
    kick_wait: 2400
    kick_tries: 2
    djeep_url: "http://10.127.52.2:8000/api"

- name: Wait for ssh to come back up
  wait_for:
    port: 22
    timeout: 300

- name: Ansible ping node post reboot
  ping:
