---
- name: install git
  apt:
    pkg: git
    state: latest

- name: Configure git identity
  tags:
    - rpc
    - git
  shell: >
    git config --global user.email "jenkins@propter.net";
    git config --global user.name "Jenkins"

- name: Delete RPC repo
  tags:
    - rpc
    - git
  command:
    rm -rf {{rpc_repo_dir}}

- name: Clone stackforge repo
  tags:
    - rpc
    - git
  git: >
    repo={{rpc_repo_url}}
    dest={{rpc_repo_dir}}

- name: Fetch origin
  tags:
    - rpc
    - git
  command: >
    git fetch origin
    chdir={{rpc_repo_dir}}

- name: Checkout target branch
  tags:
    - rpc
    - git
  command: >
    git checkout {{os_ansible_branch}}
    chdir={{rpc_repo_dir}}

- name: Checkout target tag
  tags:
    - rpc
    - git
  command: >
    git checkout {{latest_tag}}
    chdir={{rpc_repo_dir}}
  when: LATEST_TAG is defined

- name: Get change from gerrit
  tags:
    - rpc
    - git
  shell:
    git fetch https://review.openstack.org/stackforge/os-ansible-deployment {{gerrit_refspec}}
  args:
    chdir: "{{rpc_repo_dir}}"
  when: gerrit_refspec is defined

- name: Merge Review
  tags:
    - rpc
    - git
  command: >
    git merge FETCH_HEAD
    chdir={{rpc_repo_dir}}
  when: gerrit_refspec is defined
