---

## --------- [ Prepare Cluster ] ---------------

- hosts: all
  user: root
  vars_files:
    - vars/packages.yml
  roles:
    - packages
  tags: prepare

- hosts: all
  user: root
  vars_files:
    - vars/pip.yml
  roles:
    - pip
  tags: prepare

- hosts: all
  user: root
  roles:
    - networking
  tags: prepare

- hosts: all
  tasks:
    - name: Create cinder volumes vg
      lvg:
        vg: "{{item.name}}"
        pvs: "{{item.device}}"
      with_items: vgs
  tags: prepare

- hosts: all
  tags: prepare
  user: root
  roles:
    - configure-rpc-swift-lvs
    - setup-git

- hosts: infrastructure[0]
  tags: prepare
  user: root
  roles:
    - role: run-script-from-os-ansible-deployment
      script_name: bootstrap-ansible

- hosts: all
  tags: prepare
  user: root
  roles:
    - configure-rpc-compute
    - configure-rpc-swift

## --------- [ Run os-ansible-deployment ] ---------------
- hosts: infrastructure[0]
  tags: run
  roles:
    - role: run-script-from-os-ansible-deployment
      script_name: run-playbooks
      script_env:
        DEPLOY_TEMPEST: "yes"

## --------- [ Test with tempest ] ---------------
- hosts: infrastructure[0]
  tags: test
  roles:
    - role: run-script-from-os-ansible-deployment
      script_name: run-tempest

## --------- [ Clean up nodes] ---------------
- hosts: all
  tags: clean
  roles:
    - djeep-rekick
